---
version: 1
disable_existing_loggers: False
     
# Define format of output logs (named 'simple').
formatters:
    simple:
        format: "%(name)s - %(levelname)s - %(message)s"
     
handlers:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log/game.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    stream_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

root:     
    level: INFO
    handlers: [stream_handler]